{% set name = "servicex" %}
{% set version = "3.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/servicex-{{ version }}.tar.gz
  sha256: 10fe7aa45ade9ba978563e20cf51f80aa149139423fd0b0766cd7e72e06e1f74

build:
  noarch: python
  entry_points:
    - servicex = servicex.app.main:app
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python >=3.8
    - hatchling >=1.13.0
    - pip
  run:
    - python >=3.8
    - qastle >=0.17
    - func-adl >=3.2.6
    - requests >=2.31
    - pydantic >=2.6.0
    - aiohttp-retry >=2.8.3
    - httpx >=0.24
    - miniopy-async >=1.20.1
    - tinydb >=4.7
    - google-auth >=2.17
    - typer >=0.12.1
    - pyyaml >=6.0
    - types-pyyaml >=6.0
    - importlib-metadata  # python <= 3.9
    - typing_extensions  # python <= 3.10
    - rich >=13.0.0
    - aiofile
    - make-it-sync
    - ruamel.yaml >=0.18
    - ccorp-yaml-include-relative-path >=0.0.4
    - filelock >=3.12.0
    - tenacity >=9.0.0

test:
  imports:
    - servicex
  commands:
    - pip check
    - servicex --help
  requires:
    - pip

about:
  home: https://github.com/ssl-hep/ServiceX_frontend
  summary: Python SDK and CLI Client for ServiceX
  license: BSD-3-Clause
  license_file: LICENSE
  doc_url: https://servicex-frontend.readthedocs.io/
  dev_url: https://github.com/ssl-hep/ServiceX_frontend


extra:
  recipe-maintainers:
    - matthewfeickert
    - gordonwatts
    - ponyisi
    - BenGalewsky
